### ISSUE TITLE
عدم نمایش صحیح محتوای اصلی در صفحه ویرایشگر

### ISSUE THREAD

**Issue by maghajani** [Hesammousavi/PersianAdminLTE#2]
در صفحه ویرایشگر به صورت پیش فرض پنل سمت چپ باز است که باعث می شود محتوای اصلی زیر پنل سمت راست برود. مانند تصویر زیر
https://pasteboard.co/HSb6i9a.png

**Comment by hmoradian** [comment]
بخاطر اینه که پنل تنظیمات قالب در صفحه ویرایشگر بصورت پیش فرض نمایش داده میشه و ستون محتویات رو به سمت راست حرکت میده و راه حلش اینه که مخفی بشه.

![image](https://user-images.githubusercontent.com/30568120/51606384-0768b900-1f27-11e9-97f5-a5585e6d472d.png)

**Comment by Arsham-rmz** [comment]
باگ تداخل با کتابخونه WYSIHTML5 هست
