### ISSUE TITLE
استفاده به صورت ltr

### ISSUE THREAD

**Issue by rbsdotnet** [Hesammousavi/PersianAdminLTE#4]
سلام
ممنون بابت ارائه این پنل زیبا و عالی
میخواستم بدونم میشه از این پنل در حالت ltr هم استافده کرد؟ و اینکه چه بخش هایی باید تغییر کنه؟

**Comment by hashemsh** [comment]
follow the link for ltr theme 
[orginal theme ](https://adminlte.io/)
